import type { Metadata } from 'next';
import QueryProvider from '@/providers/query-provider';
import React from 'react';
import Navbar from '@/components/Navbar';
import { ThemeProvider } from '@/providers/theme-provider';

export const metadata: Metadata = {
  title: 'Authenticated',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <ThemeProvider attribute="class"
            defaultTheme="system"
            enableSystem>
        <Navbar />
        {children}
      </ThemeProvider>
    </QueryProvider>
  );
}
